# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy
import json

def serialize_array(value):
  if isinstance(value, list):
    values = [v for v in value if v is not None and v != ""]
    if len(values) == 0:
      return None
    return json.dumps(values)
  return value

def serialize_first_value(value):
  if isinstance(value, list):
    if len(value) == 0:
      return None
    elif len(value) >= 1:
      return value[0]
  return value

class ItemPalissy(scrapy.Item):
  ACQU = scrapy.Field()
  ADRS = scrapy.Field()
  AFIG = scrapy.Field(serializer=serialize_array)
  AIRE = scrapy.Field()
  APPL = scrapy.Field()
  ATEL = scrapy.Field(serializer=serialize_array)
  AUTP = scrapy.Field()
  AUTR = scrapy.Field(serializer=serialize_array)
  BASE = scrapy.Field()
  BIBL = scrapy.Field()
  CANT = scrapy.Field()
  CATE = scrapy.Field(serializer=serialize_array)
  COM = scrapy.Field(serializer=serialize_first_value) # only 3 cases where it's an array
  COM2 = scrapy.Field() # never multiple values
  CONTACT = scrapy.Field()
  CONTIENT_IMAGE = scrapy.Field()
  COOR = scrapy.Field()
  COORM = scrapy.Field()
  COPY = scrapy.Field()
  DATE = scrapy.Field(serializer=serialize_array)
  DBOR = scrapy.Field(serializer=serialize_array)
  DENO = scrapy.Field(serializer=serialize_array)
  DENQ = scrapy.Field(serializer=serialize_array)
  DEPL = scrapy.Field()
  DESC = scrapy.Field()
  DIMS = scrapy.Field()
  DMAJ = scrapy.Field()
  DMIS = scrapy.Field()
  DOMN = scrapy.Field()
  DOSADRS = scrapy.Field()
  DOSS = scrapy.Field(serializer=serialize_first_value) # only 3 cases where it's an array
  DOSURL = scrapy.Field()
  DOSURLP = scrapy.Field()
  DOSURLPDF = scrapy.Field()
  DPRO = scrapy.Field()
  DPT = scrapy.Field() # never multiple values
  DPT_LETTRE = scrapy.Field() # never multiple values
  EDIF = scrapy.Field()
  EMPL = scrapy.Field()
  ETAT = scrapy.Field(serializer=serialize_array)
  ETUD = scrapy.Field()
  EXEC = scrapy.Field()
  EXPO = scrapy.Field()
  HIST = scrapy.Field()
  IDAGR = scrapy.Field(serializer=serialize_array)
  IMAGE = scrapy.Field()
  IMG = scrapy.Field(serializer=serialize_first_value) # only 1 with multiple values
  IMPL = scrapy.Field()
  INSC = scrapy.Field(serializer=serialize_array)
  INSEE = scrapy.Field(serializer=serialize_first_value) # only 5 with multiple values
  INTE = scrapy.Field()
  JDAT = scrapy.Field() # never multiple values
  LARC = scrapy.Field()
  LIENS = scrapy.Field(serializer=serialize_array)
  LIEU = scrapy.Field()
  LINHA = scrapy.Field(serializer=serialize_first_value) # only 1 with multiple values
  LMDP = scrapy.Field()
  LOCA = scrapy.Field()
  LREG = scrapy.Field() # never multiple values
  MANQUANT = scrapy.Field() # never multiple values
  MATR = scrapy.Field(serializer=serialize_array)
  MFICH = scrapy.Field(serializer=serialize_first_value) # only one with multiple values
  MICR = scrapy.Field()
  MOSA = scrapy.Field()
  NART = scrapy.Field()
  NINV = scrapy.Field()
  NOMS = scrapy.Field(serializer=serialize_array)
  NUMA = scrapy.Field()
  NUMP = scrapy.Field()
  OBS = scrapy.Field()
  ORIG = scrapy.Field()
  PAPP = scrapy.Field()
  PARN = scrapy.Field(serializer=serialize_array)
  PART = scrapy.Field(serializer=serialize_array)
  PDEN = scrapy.Field(serializer=serialize_array)
  PDIM = scrapy.Field()
  PERS = scrapy.Field(serializer=serialize_array)
  PETA = scrapy.Field()
  PHOTO = scrapy.Field()
  PINS = scrapy.Field()
  PINT = scrapy.Field()
  PLOC = scrapy.Field()
  POP_ARRETE_PROTECTION = scrapy.Field() # never multiple values
  POP_COMMENTAIRES = scrapy.Field(serializer=serialize_array)
  POP_CONTIENT_GEOLOCALISATION = scrapy.Field()
  POP_COORDINATES_POLYGON = scrapy.Field()
  POP_COORDONNEES = scrapy.Field()
  POP_DOSSIER_PROTECTION = scrapy.Field()
  POP_DOSSIER_VERT = scrapy.Field()
  POP_FLAGS = scrapy.Field()
  POP_IMPORT = scrapy.Field(serializer=serialize_array)
  PPRO = scrapy.Field()
  PRECISION_JURIDIQUE = scrapy.Field()
  PREP = scrapy.Field()
  PRODUCTEUR = scrapy.Field()
  PROT = scrapy.Field()
  REF = scrapy.Field()
  REFE = scrapy.Field(serializer=serialize_first_value) # only one with multiple values
  REFJOC = scrapy.Field() # never multiple values
  REFM = scrapy.Field()
  REFMUS = scrapy.Field() # never multiple values
  REFP = scrapy.Field(serializer=serialize_array)
  REG = scrapy.Field(serializer=serialize_first_value) # only one with multiple values
  RENP = scrapy.Field() # never multiple values
  RENV = scrapy.Field(serializer=serialize_array)
  REPR = scrapy.Field(serializer=serialize_array)
  SCLD = scrapy.Field() # never multiple values
  SCLE = scrapy.Field(serializer=serialize_array)
  SCLX = scrapy.Field(serializer=serialize_array)
  SOUR = scrapy.Field()
  STAD = scrapy.Field(serializer=serialize_array)
  STAT = scrapy.Field(serializer=serialize_array)
  STRU = scrapy.Field(serializer=serialize_array)
  THEM = scrapy.Field()
  TICO = scrapy.Field()
  TITR = scrapy.Field()
  TOUT = scrapy.Field()
  VIDEO = scrapy.Field(serializer=serialize_array)
  VOLS = scrapy.Field()
  WADRS = scrapy.Field()
  WCOM = scrapy.Field(serializer=serialize_first_value) # only 6 with multiple values
  WEB = scrapy.Field()
  WRENV = scrapy.Field()
  ZONE = scrapy.Field()

class ItemPalissyToMerimee(scrapy.Item):
  REF_PALISSY = scrapy.Field()
  REF_MERIMEE = scrapy.Field()

class ItemPalissyToMemoire(scrapy.Item):
  REF_PALISSY = scrapy.Field()
  REF_MEMOIRE = scrapy.Field()
  NAME = scrapy.Field()
  COPY = scrapy.Field()
  URL = scrapy.Field()

class ItemMemoire(scrapy.Item):
  ACQU = scrapy.Field()
  ADPHOT = scrapy.Field()
  ADRESSE = scrapy.Field(serializer=serialize_array)
  AIRE = scrapy.Field()
  ANUMOR = scrapy.Field()
  ANUMP = scrapy.Field()
  ANUMTI = scrapy.Field()
  AUT = scrapy.Field(serializer=serialize_array)
  AUTG = scrapy.Field(serializer=serialize_array)
  AUTOEU = scrapy.Field(serializer=serialize_array)
  AUTOR = scrapy.Field(serializer=serialize_array)
  AUTP = scrapy.Field(serializer=serialize_array)
  AUTR = scrapy.Field(serializer=serialize_array)
  AUTTI = scrapy.Field(serializer=serialize_array)
  BASE = scrapy.Field()
  CHRONO = scrapy.Field()
  CINEPROD = scrapy.Field()
  COM = scrapy.Field(serializer=serialize_array)
  CONTACT = scrapy.Field()
  CONTIENT_IMAGE = scrapy.Field()
  COPY = scrapy.Field()
  COTECOR = scrapy.Field(serializer=serialize_array)
  COTECP = scrapy.Field()
  COTECTI = scrapy.Field()
  COULEUR = scrapy.Field()
  DATD = scrapy.Field()
  DATG = scrapy.Field()
  DATIMM = scrapy.Field()
  DATOEU = scrapy.Field(serializer=serialize_array)
  DATOR = scrapy.Field()
  DATPV = scrapy.Field()
  DATTI = scrapy.Field()
  DENO = scrapy.Field()
  DIFF = scrapy.Field()
  DMAJ = scrapy.Field()
  DMIS = scrapy.Field()
  DOC = scrapy.Field()
  DOM = scrapy.Field(serializer=serialize_array)
  DPT = scrapy.Field(serializer=serialize_array)
  DPT_LETTRE = scrapy.Field(serializer=serialize_array)
  ECH = scrapy.Field()
  EDIARCH = scrapy.Field()
  EDIF = scrapy.Field()
  EMET = scrapy.Field()
  EXPO = scrapy.Field()
  FORMAT = scrapy.Field()
  FORMATOR = scrapy.Field()
  FORMATTI = scrapy.Field()
  IDPROD = scrapy.Field()
  IMG = scrapy.Field()
  INSEE = scrapy.Field(serializer=serialize_array)
  JDATPV = scrapy.Field()
  LAUTP = scrapy.Field()
  LBASE = scrapy.Field(serializer=serialize_array)
  LBASE2 = scrapy.Field()
  LEG = scrapy.Field()
  LEG2 = scrapy.Field()
  LIB = scrapy.Field()
  LIENS = scrapy.Field()
  LIEU = scrapy.Field()
  LIEUCOR = scrapy.Field()
  LIEUCP = scrapy.Field()
  LIEUCTI = scrapy.Field()
  LIEUORIG = scrapy.Field()
  LOCA = scrapy.Field()
  MARQ = scrapy.Field()
  MCGEO = scrapy.Field()
  MCL = scrapy.Field(serializer=serialize_array)
  MCPER = scrapy.Field(serializer=serialize_array)
  MENTIONS = scrapy.Field()
  MENTOR = scrapy.Field()
  MENTTI = scrapy.Field()
  MOSA = scrapy.Field()
  NEGPOS = scrapy.Field()
  NOMSN = scrapy.Field()
  NUM = scrapy.Field()
  NUMAUTP = scrapy.Field()
  NUMCD = scrapy.Field()
  NUMF = scrapy.Field()
  NUMI = scrapy.Field()
  NUMOP = scrapy.Field()
  NUMOR = scrapy.Field()
  NUMP = scrapy.Field()
  NUMSITE = scrapy.Field()
  NUMTI = scrapy.Field()
  NUMVERS = scrapy.Field()
  NVD = scrapy.Field()
  OBJT = scrapy.Field()
  OBS = scrapy.Field()
  OBSOR = scrapy.Field()
  OBSTI = scrapy.Field()
  PAYS = scrapy.Field(serializer=serialize_array)
  PLOC = scrapy.Field()
  POP_FLAGS = scrapy.Field(serializer=serialize_array)
  POP_IMPORT = scrapy.Field(serializer=serialize_array)
  PRECOR = scrapy.Field()
  PRODUCTEUR = scrapy.Field()
  PUBLI = scrapy.Field()
  REF = scrapy.Field()
  REFIM = scrapy.Field()
  REFIMG = scrapy.Field()
  REFJOC = scrapy.Field(serializer=serialize_array)
  REFMUS = scrapy.Field(serializer=serialize_array)
  REG = scrapy.Field(serializer=serialize_array)
  RENV = scrapy.Field()
  REPRO = scrapy.Field()
  ROLE = scrapy.Field()
  SCLE = scrapy.Field(serializer=serialize_array)
  SENS = scrapy.Field()
  SERIE = scrapy.Field(serializer=serialize_array)
  SITE = scrapy.Field()
  STRUCT = scrapy.Field()
  SUJET = scrapy.Field()
  SUP = scrapy.Field()
  TECHN = scrapy.Field()
  TECHOR = scrapy.Field()
  TECHTI = scrapy.Field()
  THEATRE = scrapy.Field()
  TICO = scrapy.Field()
  TIREDE = scrapy.Field()
  TITRE = scrapy.Field()
  TOUT = scrapy.Field()
  TRL = scrapy.Field()
  TYP = scrapy.Field()
  TYPDOC = scrapy.Field()
  TYPEIMG = scrapy.Field()
  TYPSUPP = scrapy.Field()
  VIDEO = scrapy.Field()
  VUECD = scrapy.Field()
  WADRS = scrapy.Field(serializer=serialize_array)
  WCOM = scrapy.Field(serializer=serialize_array)
  WEB = scrapy.Field()

class ItemMerimee(scrapy.Item):
  ACMH = scrapy.Field()
  ACTU = scrapy.Field()
  ACURL = scrapy.Field()
  ADRS = scrapy.Field()
  AFFE = scrapy.Field()
  AIRE = scrapy.Field()
  APPL = scrapy.Field()
  APRO = scrapy.Field(serializer=serialize_array)
  ARCHEO = scrapy.Field()
  AUTP = scrapy.Field(serializer=serialize_array)
  AUTR = scrapy.Field(serializer=serialize_array)
  BASE = scrapy.Field()
  CADA = scrapy.Field(serializer=serialize_array)
  CANT = scrapy.Field()
  COLL = scrapy.Field(serializer=serialize_array)
  COM = scrapy.Field(serializer=serialize_array)
  CONTACT = scrapy.Field()
  CONTIENT_IMAGE = scrapy.Field()
  COOR = scrapy.Field()
  COORM = scrapy.Field()
  COPY = scrapy.Field(serializer=serialize_array)
  COUV = scrapy.Field(serializer=serialize_array)
  DATE = scrapy.Field(serializer=serialize_array)
  DBOR = scrapy.Field()
  DENO = scrapy.Field(serializer=serialize_array)
  DENQ = scrapy.Field()
  DEPL = scrapy.Field()
  DESC = scrapy.Field()
  DIMS = scrapy.Field()
  DLAB = scrapy.Field()
  DMAJ = scrapy.Field()
  DMIS = scrapy.Field()
  DOMN = scrapy.Field(serializer=serialize_first_value) # only 4 with multiple values
  DOSADRS = scrapy.Field()
  DOSS = scrapy.Field()
  DOSURL = scrapy.Field()
  DOSURLPDF = scrapy.Field()
  DPRO = scrapy.Field()
  DPT = scrapy.Field(serializer=serialize_first_value) # only 20 with multiple values
  DPT_LETTRE = scrapy.Field(serializer=serialize_first_value) # only 17 with multiple values
  EDIF = scrapy.Field()
  ELEV = scrapy.Field(serializer=serialize_array)
  ENER = scrapy.Field(serializer=serialize_array)
  ESCA = scrapy.Field(serializer=serialize_array)
  ETAG = scrapy.Field(serializer=serialize_array)
  ETAT = scrapy.Field(serializer=serialize_array)
  ETUD = scrapy.Field(serializer=serialize_array)
  GENR = scrapy.Field(serializer=serialize_array)
  HIST = scrapy.Field()
  HYDR = scrapy.Field()
  IDAGR = scrapy.Field()
  IMAGE = scrapy.Field()
  IMG = scrapy.Field(serializer=serialize_first_value) # only 2 with multiple values
  IMPL = scrapy.Field(serializer=serialize_first_value) # only 64 with multiple values
  INSEE = scrapy.Field(serializer=serialize_first_value) # only 233 with multiple values
  INTE = scrapy.Field(serializer=serialize_array)
  JATT = scrapy.Field(serializer=serialize_array)
  JDAT = scrapy.Field(serializer=serialize_array)
  LIENS = scrapy.Field(serializer=serialize_array)
  LIEU = scrapy.Field()
  LINHA = scrapy.Field() # never with multiple values
  LMDP = scrapy.Field()
  LOCA = scrapy.Field()
  LREG = scrapy.Field() # never with multiple values
  MFICH = scrapy.Field()
  MHPP = scrapy.Field()
  MICR = scrapy.Field()
  MOSA = scrapy.Field()
  MURS = scrapy.Field(serializer=serialize_array)
  NBOR = scrapy.Field()
  NOMS = scrapy.Field(serializer=serialize_array)
  OBS = scrapy.Field()
  PAFF = scrapy.Field()
  PARN = scrapy.Field(serializer=serialize_array)
  PART = scrapy.Field(serializer=serialize_array)
  PDEN = scrapy.Field()
  PERS = scrapy.Field(serializer=serialize_array)
  PINT = scrapy.Field()
  PLAN = scrapy.Field()
  PLOC = scrapy.Field()
  POP_ARRETE_PROTECTION = scrapy.Field(serializer=serialize_first_value) # only 40 with multiple values
  POP_CONTIENT_GEOLOCALISATION = scrapy.Field()
  POP_COORDINATES_POINT = scrapy.Field()
  POP_COORDINATES_POLYGON = scrapy.Field()
  POP_COORDONNEES = scrapy.Field()
  POP_DATE = scrapy.Field() # never with multiple values
  POP_DOSSIER_PROTECTION = scrapy.Field() # never with multiple values
  POP_DOSSIER_VERT = scrapy.Field()
  POP_FLAGS = scrapy.Field(serializer=serialize_array)
  POP_HAS_LOCATION = scrapy.Field(serializer=serialize_array)
  POP_IMPORT = scrapy.Field(serializer=serialize_array)
  PPRO = scrapy.Field()
  PREP = scrapy.Field(serializer=serialize_array)
  PRODUCTEUR = scrapy.Field()
  PROT = scrapy.Field(serializer=serialize_array)
  PSTA = scrapy.Field()
  REF = scrapy.Field()
  REFE = scrapy.Field(serializer=serialize_first_value) # only 2 with multiple values
  REFIM = scrapy.Field()
  REFJOC = scrapy.Field() # never with multiple values
  REFM = scrapy.Field()
  REFMUS = scrapy.Field(serializer=serialize_array)
  REFO = scrapy.Field(serializer=serialize_array)
  REFP = scrapy.Field(serializer=serialize_array)
  REG = scrapy.Field(serializer=serialize_first_value) # only 8 with multiple values
  REMA = scrapy.Field()
  REMP = scrapy.Field()
  RENV = scrapy.Field(serializer=serialize_array)
  REPR = scrapy.Field()
  RFPA = scrapy.Field()
  SCLD = scrapy.Field(serializer=serialize_array)
  SCLE = scrapy.Field(serializer=serialize_array)
  SCLX = scrapy.Field(serializer=serialize_array)
  SITE = scrapy.Field()
  STAT = scrapy.Field()
  TECH = scrapy.Field(serializer=serialize_array)
  THEM = scrapy.Field()
  TICO = scrapy.Field()
  TOIT = scrapy.Field(serializer=serialize_array)
  TOUT = scrapy.Field()
  TYPO = scrapy.Field()
  VERT = scrapy.Field()
  VIDEO = scrapy.Field()
  VISI = scrapy.Field(serializer=serialize_first_value) # only 60 with multiple values
  VOCA = scrapy.Field()
  VOUT = scrapy.Field(serializer=serialize_array)
  WADRS = scrapy.Field()
  WCOM = scrapy.Field(serializer=serialize_array)
  WEB = scrapy.Field()
  WRENV = scrapy.Field()
  ZONE = scrapy.Field()

class ItemMerimeeToMemoire(scrapy.Item):
  REF_MERIMEE = scrapy.Field()
  REF_MEMOIRE = scrapy.Field()
  NAME = scrapy.Field()
  COPY = scrapy.Field()
  URL = scrapy.Field()
